#!/bin/bash

curr_dir=${0%/*}
source $curr_dir/config.sh

MIN_PORT=$PORT
MAX_PORT=$(($MIN_PORT + $NUM_INSTANCES - 1))

if [ $# -lt 1 ]; then
cat << EOF
Expected at least 1 bulk file
Usage:
    $0 <bulk_file> ... <bulk_file>
EOF
    exit 1
fi

while [ $# -gt 0 ]; do
    if [ -f "$1.ok" ] || [ -f "$1.err" ]; then
        echo Skipping "$1": already processed
    else
        TMP_DIR="/tmp/bulk-split"
        rm -rf $TMP_DIR
        mkdir -p $TMP_DIR
        split --lines 100 "$1" "$TMP_DIR/file"
        for file in $TMP_DIR/*; do
            PORT=$(shuf -i $MIN_PORT-$MAX_PORT -n 1)
            OUTPUT="$(curl -s -S -XPOST $HOST:$PORT/_bulk?index=$INDEX\&type=doc --data-binary @$file 2>&1)"
            echo "$OUTPUT" | grep '"errors":false' &> /dev/null || {
                echo Error at "$1"
                echo $OUTPUT > "$1.err"
                break
            }
        done
        rm -rf $TMP_DIR
        [[ -r "$1.err" ]] || {
            echo Processed "$1"
            touch "$1.ok"
        }
    fi

    shift
done

curl -s -XPOST $HOST:$PORT/$INDEX/_refresh &> /dev/null
