name: CI

on: [push, pull_request]

jobs:
  buildlinux:
    runs-on: ubuntu-16.04
    name: 'Ubuntu / ${{ matrix.compiler }}'
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v2
    - name: Setup dependencies
      run: |
        sudo apt-get -y install \
          cmake \
          make \
          pkg-config \
          libmicrohttpd-dev \
          libxml2-dev \
          libleveldb-dev \
          libsnappy-dev \
          libjson0-dev \
          libhtmlcxx-dev \
          libicu-dev \
          libcurl4-gnutls-dev \
          netcat \
          curl

    - run: make
      env:
        CC: ${{ matrix.compiler }}
    - run: make test
      env:
        CC: ${{ matrix.compiler }}
  buildmac:
    runs-on: macos-latest
    name: 'macOS / ${{ matrix.compiler }}'
    strategy:
      matrix:
        compiler: [gcc]
    steps:
    - uses: actions/checkout@v2
    - name: Setup dependencies
      run: |
        brew install \
          cmake \
          curl \
          gcc \
          gnutls \
          htmlcxx \
          icu4c \
          json-c \
          leveldb \
          libmicrohttpd \
          libxml2 \
          make \
          netcat \
          pkg-config \
          snappy \
        && brew link --force icu4c

    - run: make
      env:
        CC: ${{ matrix.compiler }}
    - run: make test
      env:
        CC: ${{ matrix.compiler }}
